name: Tests IPA
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docu/*'

jobs:
  test-ipa-nodejs:
    name: IPA sur Node.js
    runs-on: ubuntu-latest
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v3

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Installer playwright
        run: npx playwright install

      - name: Vérifier les tests
        run: pnpm test:node

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v2
  
  test-ipa-navig:
    name: IPA sur le navigateur
    runs-on: ubuntu-latest
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v3

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Installer playwright
        run: npx playwright install

      - name: Vérifier les tests
        run: pnpm test:navig

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v2

  test-ipa-electron-principal:
    name: IPA sur Électron principal
    runs-on: ubuntu-latest
    needs: test-ipa-nodejs
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v3

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Installer playwright
        run: npx playwright install

      - name: Vérifier les tests
        run: pnpm test:électron-principal

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v2
